### ISSUE TITLE
Support for .swifttemplate format?

### ISSUE THREAD

**Issue by Sajjon** [SwiftGen/templates#88]
Is it possible to use `.swifttemplate` format (instead of `.stencil`), as used by Sourcery? :) I tried passing a template written in `.swifttemplate` using the `TemplatePath` argument, but it did not recognize the template code.

**Comment by Liquidsoul** [comment]
SwiftTemplates are really specific to Sourcery and their implementation are tightly coupled to it, mostly because they use the `SourceryRuntime` framework you use in your templates.
Implement inf them in SwiftGen would mean having such a module allowing easy access to what stencil offers today by just using a dictionary.
In any case, this is not really planned at the moment 😊

**Comment by djbe** [comment]
Closing this for now as it is not a feature we're planning to implement, but if more people'd want it, a new issue can be opened for it in the [SwiftGen](https://github.com/SwiftGen/SwiftGen) repository.
